#!/bin/sh
#
# Fuck 8-) Not working in 'sh -e' 

# PROVIDE: ae3d
# REQUIRE: LOGIN DAEMON FILESYSTEMS
# KEYWORD: shutdown

. /etc/rc.subr

name=ae3d
rcvar=ae3d_enable

load_rc_config $name

pidfile="/usr/local/ae3/.daemon.pid"

extra_commands="jpid"
# jpid_cmd='echo $(pgrep -P `cat $pidfile`) || false'
jpid_cmd='echo $(test -f "/etc/passwd" && test -f "$pidfile" && ( pgrep -P $(pgrep -P $(cat "$pidfile") -n) || "failed!") || echo "not running.")'

ae3d_enable="${ae3d_enable:-"NO"}"
ae3d_chdir="${ae3d_chdir:-"/usr/local/ae3"}"
ae3d_user="${ae3d_user:-"ae3"}"
ae3d_group="${ae3d_group:-"ae3"}"

ae3d_command="/usr/local/share/ae3/bin/run"
bash_command="`which bash`"

export HOME=`pw usershow "$ae3d_user" | cut -f9 -d:`

# for rc subr
procname="$bash_command"

command="/usr/sbin/daemon"
command_args="-f -S -p $pidfile $bash_command $ae3d_command --start server"

required_files="$ae3d_command $bash_command"

start_precmd="touch $pidfile ; chown $ae3d_user $pidfile ; chmod 644 $pidfile"
stop_postcmd="echo AE3 daemon service is stopped."

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:

run_rc_command "$1"
